name: Initialize project tracking

on:
  - fork
  - workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Fall 2025 deadlines for milestones (23:59 Toronto --> 03:59 UTC)
  M1:    "2025-10-13T03:59:59.0Z"
  M2:    "2025-11-10T03:59:59.0Z"
  FINAL: "2025-12-05T03:59:59.0Z"
  
jobs:
  init-milestones:

    runs-on: ubuntu-latest
    steps:
      - name: Create Milestone 1
        run: |
          gh api \
            repos/${{ github.repository }}/milestones \
            -f title="Milestone 1" \
            -f state="open" \
            -f description="First Window of Opportunity for feedback" \
            -f due_on="${{ env.M1 }}"

      - name: Create Milestone 2
        run: |
          gh api \
            repos/${{ github.repository }}/milestones \
            -f title="Milestone 2" \
            -f state="open" \
            -f description="Second Window of Opportunity for feedback" \
            -f due_on="${{ env.M2 }}"

      - name: Create Milestone 3
        run: |
          gh api \
            repos/${{ github.repository }}/milestones \
            -f title="Final Delivery" \
            -f state="open" \
            -f description="Delivery of the complete document" \
            -f due_on="${{ env.FINAL }}"
