name: Delete All Issues, Milestones, and Labels

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  cleanup-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all issues
        run: |
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"

          echo "Fetching all open issues..."
          ISSUES=$(gh api repos/$REPO_OWNER/$REPO_NAME/issues --jq ".[].number")
          for NUMBER in $ISSUES; do
            echo "Deleting issue #$NUMBER"
            gh api -X DELETE repos/$REPO_OWNER/$REPO_NAME/issues/$NUMBER
          done

      - name: Delete all milestones
        run: |
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"

          echo "Fetching all milestones..."
          MILESTONES=$(gh api repos/$REPO_OWNER/$REPO_NAME/milestones --jq ".[].number")
          for NUMBER in $MILESTONES; do
            echo "Deleting milestone #$NUMBER"
            gh api -X DELETE repos/$REPO_OWNER/$REPO_NAME/milestones/$NUMBER
          done

      - name: Delete all labels
        run: |
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"

          echo "Fetching all labels..."
          LABELS=$(gh api repos/$REPO_OWNER/$REPO_NAME/labels --jq ".[].name")
          for LABEL in $LABELS; do
            echo "Deleting label '$LABEL'"
            gh api -X DELETE repos/$REPO_OWNER/$REPO_NAME/labels/"$LABEL"
          done